config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    member do
      get 'add_membership'
      delete 'remove_member'
      get 'approve_request'
      get 'reject_request'
    end
  end

  root 'home#index'

  resources :issues, only: :index do
    get 'filter', on: :collection
    get 'history', on: :member
    resources :comments, shallow: true
    resources :documents, except: :destroy
  end

  resources :projects do
    resources :documents, except: :destroy
    resources :comments, shallow: true
    resources :issue_types, except: :destroy
    resources :project_memberships, only: %i[index create], as: 'members'
    resources :issues, only: [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :documents do
    delete :destroy
  end

  resources :comments, only: [:edit, :update, :destroy]

  resources :issue_states do
    get :autocomplete_issue_title, on: :collection
  end

  resources :project_memberships, only: :destroy do
    collection do
      get 'search'
    end
  end

  resources :issue_types do
    get :autocomplete_project_title, on: :collection
  end

  get 'user_companies/find', to: 'user_companies#find'
  post 'user_companies/find', to: 'user_companies#find_user_by_email'
  get 'user_companies/show_companies', to: 'user_companies#show_companies', as: :show_companies
  get 'sidebar_toggle/:is_collapsed', to: 'application#sidebar_toggle'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    get 'users/sign_up/verify_subdomain_availability', to: 'users/registrations#verify_subdomain_availability'
  end

  get 'reports/issues', to: 'reports#issues', as: 'issues_report'
  get 'workplace', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/issues', to: 'dashboard#issues', as: 'dashboard_issues'

  resources :members do
    member do
      get 'privileges', action: 'privileges_show'
      get 'change_password_form', action: 'show_change_password_form'
      put 'change_password', action: 'change_password'
    end
    collection do
      get 'privileges'
    end
  end

  resources :issue_watchers do
    collection do
      get 'search'
    end
  end
end

app/models/issue.rb
# Model Class
class Issue < ActiveRecord::Base
  sequenceid :company, :issues
  audited associated_with: :project

  PRIORITY = {
    Low: 0,
    Medium: 1,
    High: 2
  }.freeze

  scope :group_by_issue_state, -> { joins(:issue_state).group(:name) }
  scope :search, ->(filter_params, search_keyword) { where(filter_params).where('title LIKE ?', "%#{sanitize_sql_like(search_keyword)}%") }

  after_save :send_email
  paginates_per 7

  # Validations
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :progress, presence: true, length: { minimum: 1, maximum: 5 }
  validates :priority, presence: true
  validates :issue_state_id, presence: true
  validates :issue_type_id, presence: true

  validate :due_date_after_start_date

  belongs_to :company
  belongs_to :project, counter_cache: true
  belongs_to :issue_state
  has_many   :issue_states
  belongs_to :issue_type

  # An issue belongs to an admin (creator)
  belongs_to :creator, class_name: 'User' # creator

  # An issue can be assigned to a member (assignee)
  belongs_to :assignee, class_name: 'User' # assignee

  # An issue can have many sub issues
  has_many   :sub_issues, foreign_key: 'parent_issue_id', class_name: 'Issue'
  belongs_to :parent_issue, class_name: 'Issue'

  has_many   :documents, as: :documentable, dependent: :destroy
  has_many   :comments, as: :commentable, dependent: :destroy

  # Polymorphic Watchers
  has_many   :issue_watchers, dependent: :destroy

  has_many   :watcher_users, through: :issue_watchers, source: :watcher,
  source_type: 'User', class_name: 'User'
  has_many   :watcher_teams, through: :issue_watchers, source: :watcher,
  source_type: 'Team', class_name: 'Team'

  # Validates date
  def due_date_after_start_date
    return if due_date.blank? || start_date.blank?

    if due_date < start_date
      errors.add(:due_date, 'must be after the start date')
    end
  end

  # Helper method for sending email
  def send_email
    return if Rails.env.test?

    emails = []
    issue_watchers.each do |issue_watcher|
      if issue_watcher.watcher.is_a?(User)
        user_email = User.find_by(id: issue_watcher.watcher_id).email
        emails << user_email
      elsif issue_watcher.watcher.is_a?(Team)
        team = Team.find_by(id: issue_watcher.watcher_id)
        team_emails = team.users.pluck(:email)
        emails += team_emails
      end
    end
    # Fetching creator's email
    emails << creator.email

    # Fetching assignee's email
    emails << assignee.email if assignee.present?

    # Removing duplicates and nil values
    emails = emails.compact.uniq
    emails.each do |email|
      IssueMailer.delay.notify(email, sequence_num, company_id)
    end
  end
end

app/models/issue_type.rb
class IssueType < ActiveRecord::Base
  DEFAULT_ISSUE_TYPES = %w[Improvement New\ Feature].freeze

  validates(:name, presence: true,
                   uniqueness: { scope: [:project_id, :company_id], case_sensitive: false },
                   length: { minimum: MIN_LENGTH, maximum: 20 })
  validates :company_id, presence: true

  has_many :issues
  belongs_to :company
  belongs_to :project

  scope :project_issue_types, ->(project_id) { where(project_id: [project_id, nil]) }
  scope :for_projects, ->(project) { where(project_id: project.id) }

  def orphan_issues_count(project_id)
    issues.where.not(project_id: project_id).count
  end

  def dependent_issues_present?
    issues.count > 0
  end
end

app/controllers/issues_controller.rb
# Issues Controller
class IssuesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :project, find_by: :sequence_num
  load_and_authorize_resource through: :project, find_by: :sequence_num, except: %i[index history filter]
  load_and_authorize_resource find_by: :sequence_num, only: %i[index history filter]

  # GET /issues
  def index
    if params[:issue_type_id].present?
      @issues = current_tenant.issues.where(issue_type_id: params[:issue_type_id])
    elsif params[:issue_state_id].present?
      @issues = current_tenant.issues.where(issue_state_id: params[:issue_state_id])
    else
      add_breadcrumb 'All Issues', :issues_path
      @projects = current_user.visible_projects
      @issues = @issues.order(:project_id).page(params[:page])
      @issue_types = current_tenant.issue_types.all
      @issue_states = current_tenant.issue_states.all
      @assignees = current_tenant.users.all
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /issues/filter
  def filter
    @issues = Issue.search(search_params, params[:search_issue]).page(params[:page])
    respond_to do |format|
      format.js
    end
  end

  # GET projects/:project_id/issues/new
  def new
    @assignees = current_tenant.users.all
    @issue_types = current_tenant.issue_types.project_issue_types(@project.id)
    @issue_states = current_tenant.issue_states.all
    add_breadcrumb 'Projects', :projects_path
    add_breadcrumb @project.title, project_path(@project)
    add_breadcrumb 'New Issue', :new_project_issue_path
    respond_to do |format|
      format.html
    end
  end

  # GET projects/:project_id/issues/:id
  def show
    add_breadcrumb 'Projects', :projects_path
    add_breadcrumb @issue.project.title, project_path(@issue.project)
    add_breadcrumb @issue.title, :project_issue_path
    @document = Document.new
    @comment = Comment.new
    @comments = @issue.comments
    respond_to do |format|
      format.html
    end
  end

  # GET projects/:project_id/issues/:id/edit
  def edit
    add_breadcrumb 'Projects', :projects_path
    add_breadcrumb @issue.project.title, project_path(@issue.project)
    add_breadcrumb @issue.title, :project_issue_path
    add_breadcrumb 'Edit', :edit_project_issue_path
    @project = @issue.project
    @assignees = current_tenant.users.all
    @issue_types = current_tenant.issue_types.project_issue_types(@project.id)
    @issue_states = current_tenant.issue_states.all
    respond_to do |format|
      format.html
    end
  end

  # PUT projects/:project_id/issues/:id
  def update
    if @issue.update(issue_params)
      flash[:notice] = t('issues.update.notice')
      respond_to do |format|
        format.html { redirect_to project_issue_path(@issue.project, @issue) }
      end
    else
      add_breadcrumb 'Projects', :projects_path
      add_breadcrumb @issue.project.title, project_path(@issue.project)
      add_breadcrumb @issue.title, :project_issue_path
      add_breadcrumb 'Edit', :edit_project_issue_path
      @assignees = current_tenant.users.all
      @issue_types = current_tenant.issue_types.all
      @issue_states = current_tenant.issue_states.all
      @project = @issue.project
      flash.now[:error] = @issue.errors.full_messages
      render 'edit'
    end
  end

  # POST projects/:project_id/issues
  def create
    @issue.creator_id = current_user.id
    if @issue.save
      flash[:notice] = t('issues.create.notice')
      respond_to do |format|
        format.html { redirect_to project_issue_path(@issue.project, @issue) }
      end
    else
      add_breadcrumb 'Projects', :projects_path
      add_breadcrumb @project.title, project_path(@project)
      add_breadcrumb 'New Issue', :new_project_issue_path
      @assignees = current_tenant.users.all
      @issue_types = current_tenant.issue_types.all
      @issue_states = current_tenant.issue_states.all
      @project = @issue.project
      flash.now[:error] = @issue.errors.full_messages
      render 'new'
    end
  end

  # DELETE projects/:project_id/issues/:id
  def destroy
    if @issue.destroy
      flash[:notice] = t('issues.destroy.notice')
      respond_to do |format|
        format.html { redirect_to project_path(@issue.project_id) }
      end
    else
      flash.now[:error] = @issue.errors.full_messages
      render 'edit'
    end
  end

  # GET /issues/:id/history
  def history
    add_breadcrumb 'Projects', :projects_path
    add_breadcrumb @issue.project.title, project_path(@issue.project_id)
    add_breadcrumb @issue.title, project_issue_path(@issue.project_id, @issue)
    add_breadcrumb 'History', history_issue_path(@issue)
    @audits = @issue.audits
    respond_to do |format|
      format.html
    end
  end

  private

  # Permits columns of issue while adding to database
  def issue_params
    params.require(:issue)
          .permit(:title, :description, :start_date, :due_date, :progress,
                  :priority, :company_id, :creator_id, :assignee_id,
                  :parent_issue_id, :project_id, :issue_state_id,
                  :issue_type_id)
  end

  # Permits columns of issue that are not blank for search
  def search_params
    params.permit(:project_id, :assignee_id, :issue_state_id, :issue_type_id)
          .delete_if { |_key, value| value.blank? }
  end
end

app/helpers/issues_helper.rb
# issues_helper.rb
module IssuesHelper
  BADGES = ['success', 'warning', 'danger'].freeze
  KEY_TO_CLASS_MAPPINGS = { assignee_id: User,
                            issue_state_id: IssueState,
                            issue_type_id: IssueType }.freeze

  def get_priority(priority)
    Issue::PRIORITY.key(priority)
  end

  def show_priority
    Issue::PRIORITY
  end

  def get_associated_information(key, value)
    if value.blank?
      result = 'NULL'
    elsif KEY_TO_CLASS_MAPPINGS.keys.include?(key.to_sym)
      result = KEY_TO_CLASS_MAPPINGS[key.to_sym].find(value).name
    elsif key == 'progress'
      result = number_to_percentage(value, precision: 0)
    elsif key == 'priority'
      result = get_priority(value)
    else
      result = value
    end
    result
  end

  def badge_class_from_priority(priority)
    BADGES[priority]
  end

  def issue_delete_data_confirm(issue)
    watchers_count = issue.issue_watchers.count
    if watchers_count.zero?
      t('issues.confirm_delete.default')
    else
      t('issues.confirm_delete.watchers_exist_warning', watchers_count: watchers_count).pluralize(watchers_count)
    end
  end
end

app/views/issues/_form.html.erb
 <%= form_for [@project, @issue] do |f| %>
  <div class="form-group">
    <%= f.label :title do %>
      Title<span class="text-danger">*</span>
    <% end %>
    <%= f.text_field :title, class: 'form-control', maxlength: 100, required: true, minlength: 3 %>
  </div>
  <br>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', cols: 2, rows: 6, minlength: 3 %>
      </div>
    </div>
  </div>
  <hr>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :start_date %>
        <%= f.text_field :start_date, class: 'form-control', readonly: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :due_date %>
       <%= f.text_field :due_date, class: 'form-control', readonly: true %> 
      </div>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :assignee_id %>
        <%= f.select :assignee_id, assignees.collect { |assignee| [assignee.try(:name), assignee.id] }, { include_blank: 'Select an assignee' }, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :priority do %>
          Priority<span class="text-danger">*</span>
        <% end %>
        <%= f.select :priority, show_priority.collect { |key, value| [key, value] }, {}, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :issue_state_id do %>
          Issue State<span class="text-danger">*</span>
        <% end %>       
        <%= f.select :issue_state_id, issue_states.collect { |issue_state| [issue_state.try(:name), issue_state.id] }, {}, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :issue_type_id do %>
          Issue Type<span class="text-danger">*</span>
        <% end %>
        <%= f.select :issue_type_id, issue_types.collect { |issue_type| [issue_type.try(:name), issue_type.id] }, {}, class: 'form-control' %>
      </div>
    </div> 
  </div>
  <hr>
  <%= f.number_field :project_id, value: @project.id, hidden: true %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :progress do %>
          Progress<span class="text-danger">*</span>
        <% end %>
        <%= f.number_field :progress, class: 'form-control', min: 0, max: 100, step: 5, required: true %>
      </div>
    </div>
  </div>
  <hr>

  <%= f.submit({ class: 'btn btn-secondary float-right' }) %>
<% end %>

app/views/issues/_issue_audit_row.html.erb
<% if audit.action == 'update' %>
  <tr>
    <td><%= audit_counter %></td>
    <td><%= audit.created_at.strftime("%b %d %Y %I:%M %p") %></td>
    <td>
      <%= render partial: 'issue_history_nested_table_for_attribute', locals: {audit: audit} %>
    </td>
    <td>
      <%= render partial: 'issue_history_nested_table_for_from', locals: {audit: audit} %>
    </td>
    <td>
      <%= render partial: 'issue_history_nested_table_for_to', locals: {audit: audit} %>
    </td>
  </tr>  
<% end %>

app/views/issues/_issue_history_nested_table_for_attribute.html.erb
<table class="table table-sm">
  <% audit.audited_changes.keys.each do |key| %>
    <tr>
      <td>
        <%= key.titleize %>
      </td>
    </tr>
  <% end %>
</table>

app/views/issues/_issue_history_nested_table_for_from.html.erb
<table class="table table-sm">
  <% audit.audited_changes.each do |key, value| %>
    <tr>
      <td>
        <%= get_associated_information(key, value[0]) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/issues/_issue_history_nested_table_for_to.html.erb
<table class="table table-sm">
  <% audit.audited_changes.each do |key, value| %>
    <tr>
      <td>
        <%= get_associated_information(key, value[1]) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/issues/_issues.html.erb
<!-- Partial: Displays rows in a table -->
<% issues.each do |issue| %>
  <tr>
    <td><%= link_to issue.title, project_issue_path(issue.project, issue) %></td>
    <% if local_assigns[:render_project_title] %>
      <td><%= link_to issue.project.title, project_path(issue.project) %></td>
    <% end %>
    <td>
      <% if issue.assignee.present? %>
        <%= link_to issue.assignee.try(:name), member_path(issue.assignee) %>
      <% end %>
    </td>
    <td><%= issue.issue_type.try(:name) %></td>
    <td><%= issue.issue_state.try(:name) %></td>
    <td><%= get_priority(issue.priority) %></td>
    <td><%= issue.start_date %></td>
    <td><%= issue.due_date %></td>
  </tr>
<% end %>

app/views/issues/edit.html.erb
<h1>Edit Issue</h1>
<%= render partial: "form", locals: { issue: @issue, assignees: @assignees, issue_states: @issue_states, issue_types: @issue_types } %>
<%= link_to :Back, project_issue_path(@issue.project, @issue), class: 'btn btn-secondary float-right mr-2 mb-5' %>

app/views/issues/filter.js.erb
$('#issues_table').DataTable().clear().destroy();
$("#issues_list tr").remove();
$("#issues_table tbody").append('<%= j render partial: "issues", locals: { issues: @issues, render_project_title: true } %>');
$('#issues_paginator').html('<%= j paginate(@issues, remote: true).to_s %>');
$('#issues_table').DataTable({
    "paging": false,
    "info":   false,
    "searching": false
});

app/views/issues/history.html.erb
<div class="wrapper mb-4">
  <h1 class="float-left"><%= @issue.title %> History Report</h1>
  <div class="float-right" id="datatable_buttons"></div>
</div>

<div class="my-4">
  <table id="report_datatable"  class="table">
    <thead>
      <tr>
        <th scope="col">Sr#</th>
        <th scope="col">Time</th>
        <th scope="col">Attribute</th>
        <th scope="col">From</th>
        <th scope="col">To</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'issue_audit_row', collection: @audits, as: :audit %>
    </tbody>
  </table>
</div>

app/views/issues/index.html.erb
<h1>Issues</h1>
  <%= form_tag(filter_issues_path, method: 'get', remote: true, id: "issues_filter_form" ) do %>
    <div class="row">
      <div class="col-sm-3">
        <label>Projects</label>
        <%= select_tag "project_id", options_from_collection_for_select(@projects, :id, :title), class: 'form-control dropdown-toggle', include_blank: "All" %>
      </div>

      <div class="col-sm-3">
        <label>Assignee</label>
        <%= select_tag "assignee_id", options_from_collection_for_select(@assignees, :id, :first_name), class: 'form-control', include_blank: "All" %>
      </div>

      <div class="col-sm-3">
        <label>Issue State</label>
        <%= select_tag "issue_state_id", options_from_collection_for_select(@issue_states, :id, :name), class: 'form-control', include_blank: "All"%>
      </div>

      <div class="col-sm-3">
        <label>Issue Type</label>
        <%= select_tag "issue_type_id", options_from_collection_for_select(@issue_types, :id, :name), class: 'form-control', include_blank: "All"%>
      </div>
    </div>

    <div class="row mt-3 align-items-center">
      <div class="offset-sm-9 col-12 col-sm-3">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-search"></i></span>
          </div>
          <%= text_field_tag "search_issue", nil, class: 'form-control', placeholder: 'Search for title'%>
        </div>
      </div>
    </div>
  <% end %>
<br>

<table class="table table-hover" id="issues_table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Project Title</th>
      <th scope="col">Assignee</th>
      <th scope="col">Issue Type</th>
      <th scope="col">Status</th>
      <th scope="col">Priority</th>
      <th scope="col">Created</th>
      <th scope="col">Due Date</th>
    </tr>
  </thead>
  <tbody id="issues_list">
    <%= render partial: "issues", locals: { issues: @issues, render_project_title: true } %>
  </tbody>
</table>

<div id="issues_paginator" class="float-right">
    <%= paginate @issues %>
</div>

app/views/issues/index.js.erb
if (typeof issuesTable !== 'undefined'){
  issuesTable.destroy();
}

$('#custom_issues_table tbody').html('<%= j render partial: "shared/list_issues", collection: @issues, as: :issue %>');
$('#issues_modal').modal('show');

issuesTable = $('#custom_issues_table').DataTable({
    info: false,
    paging: false,
    scrollY: "50vh",
    scrollCollapse: true,
    oLanguage: {
      sEmptyTable: "No issues found"
    }
  });

app/views/issues/new.html.erb
<h1>Add Issue</h1>
<%= render partial: "form", locals: { issue: @issue, assignees: @assignees, issue_states: @issue_states, issue_types: @issue_types } %>
<%= link_to :Back, project_path(params[:project_id]), class: 'btn btn-secondary float-right mr-2 mb-5' %>

app/views/issues/show.html.erb
<div class="wrapper">
  <h2 class="float-left"><%= @issue.title %></h2>
  <% if can?(:history, @issue) %>
    <%= link_to 'History', history_issue_path(@issue), class: 'btn btn-secondary float-right' %>
  <% end %>

  <% if can?([:destroy, :search], IssueWatcher) %>
    <button type="button" class="btn btn-secondary float-right mr-2" data-toggle="modal" data-target="#remove_watchers_modal">Remove Watcher</button>
    <%= render partial: 'issue_watchers/remove_watchers_form', locals: { issue: @issue } %>
  <% end %>

  <% if can?([:create, :search], IssueWatcher) %>
    <button type="button" class="btn btn-secondary float-right mr-2" data-toggle="modal" data-target="#add_watchers_modal">Add Watcher</button>
    <%= render partial: 'issue_watchers/add_watchers_form', locals: { issue: @issue } %>
  <% end %>

  <div id="watch_button_div" class="float-right mr-2">
    <%= render partial: 'issue_watchers/watch_button', locals: { issue: @issue } %>
  </div>

  <% if can?(:destroy, @issue) %>
    <%= link_to "Delete", project_issue_path(@issue.project, @issue.sequence_num), method: :delete, data: { confirm: issue_delete_data_confirm(@issue) }, class: 'btn btn-secondary float-right mr-2', id: 'issue_delete_button' %>
  <% end %>

  <% if can?(:update, @issue) %>
    <%= link_to 'Edit', edit_project_issue_path(@issue.project, @issue.sequence_num), class: 'btn btn-secondary float-right mr-2' %>
  <% end %>
</div>
<br>
<table class="table">
  <tbody>
    <tr>
      <th scope="row" id="remove_border_top_from_th">Title:</th>
      <td><%= @issue.title %></td>
    </tr>
    <tr>
      <th scope="row">Description:</th>
      <td><%= @issue.description %></td>
    </tr>
    <tr>
      <th scope="row">Start Date:</th>
      <td><%= @issue.start_date %></td>
    </tr>
    <tr>
      <th scope="row">Due Date:</th>
      <td><%= @issue.due_date %></td>
    </tr>
    <tr>
      <th scope="row">Progress:</th>
      <td><%= @issue.progress %>%</td>
    </tr>
    <tr>
      <th scope="row">Priority:</th>
      <td><%= get_priority(@issue.priority) %></td>
    </tr>
    <tr>
      <th scope="row">State:</th>
      <td><%= @issue.issue_state.try(:name) %></td>
    </tr>
    <tr>
      <th scope="row">Assignee:</th>
      <td><span class="glyphicon glyphicon-user"></span><%= @issue.assignee.try(:name) %></td>
    </tr>
    <tr>
      <th scope="row">Issue Type:</th>
      <td><%= @issue.issue_type.try(:name) %></td>
    </tr>
  </tbody>
</table>
<br>

<ul class="nav nav-tabs mb-4" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="pill" href="#pills_document" role="tab" aria-controls="pills_document" aria-selected="false">Documents</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="pill" href="#pills_comment" role="tab" aria-controls="pills_comment" aria-selected="false">Comments</a>
  </li>
</ul>

<div class="tab-content mb-5">
  <div class="tab-pane fade show active" id="pills_document" role="tabpanel" aria-labelledby="pills_timeline_tab">
    <div class="page-header">
      <button type="button" class="btn btn-secondary float-right" data-toggle="modal" data-target="#upload_document_modal">Upload Document</button>
      <br><br><br>
      <%= render partial: 'documents/upload_document_modal' %>
      <%= render partial: "documents/show_documents", locals: { documents: @issue.documents } %>
    </div>
  </div>

  <div class="tab-pane fade" id="pills_comment" role="tabpanel" aria-labelledby="pills_timeline_tab">
    <%= render partial: 'comments/comment', locals: { commentable_object: @issue, comment: @comment, comments: @comments } %>
  </div>
</div>