config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    member do
      get 'add_membership'
      delete 'remove_member'
      get 'approve_request'
      get 'reject_request'
    end
  end

  root 'home#index'

  resources :issues, only: :index do
    get 'filter', on: :collection
    get 'history', on: :member
    resources :comments, shallow: true
    resources :documents, except: :destroy
  end

  resources :projects do
    resources :documents, except: :destroy
    resources :comments, shallow: true
    resources :issue_types, except: :destroy
    resources :project_memberships, only: %i[index create], as: 'members'
    resources :issues, only: [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :documents do
    delete :destroy
  end

  resources :comments, only: [:edit, :update, :destroy]

  resources :issue_states do
    get :autocomplete_issue_title, on: :collection
  end

  resources :project_memberships, only: :destroy do
    collection do
      get 'search'
    end
  end

  resources :issue_types do
    get :autocomplete_project_title, on: :collection
  end

  get 'user_companies/find', to: 'user_companies#find'
  post 'user_companies/find', to: 'user_companies#find_user_by_email'
  get 'user_companies/show_companies', to: 'user_companies#show_companies', as: :show_companies
  get 'sidebar_toggle/:is_collapsed', to: 'application#sidebar_toggle'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    get 'users/sign_up/verify_subdomain_availability', to: 'users/registrations#verify_subdomain_availability'
  end

  get 'reports/issues', to: 'reports#issues', as: 'issues_report'
  get 'workplace', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/issues', to: 'dashboard#issues', as: 'dashboard_issues'

  resources :members do
    member do
      get 'privileges', action: 'privileges_show'
      get 'change_password_form', action: 'show_change_password_form'
      put 'change_password', action: 'change_password'
    end
    collection do
      get 'privileges'
    end
  end

  resources :issue_watchers do
    collection do
      get 'search'
    end
  end
end

app/controllers/user_companies_controller.rb
class UserCompaniesController < ApplicationController
  # GET user_companies/find
  def find
    respond_to do |format|
      format.html { render 'user_companies/find' }
    end
  end

  # POST user_companies/find
  def find_user_by_email
    @found_users = User.unscope(where: :company_id).where(email: params[:email])

    respond_to do |format|
      format.js { render 'user_companies/find_user_by_email_response' }
    end
  end

  # GET user_companies/show_companies
  def show_companies
    @email = params[:user_email]
    @companies = Company.where(id: User.unscope(where: :company_id).where(email: @email).pluck(:company_id))
    respond_to do |format|
      format.html { render 'user_companies/show_companies' }
    end
  end
end

app/helpers/user_companies_helper.rb
module UserCompaniesHelper
end

app/views/user_companies/find.html.erb
<div class="card shodowed-card">
  <h2 class="card-header">Login</h2>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6 d-none d-sm-block text-center">
        <img src="/assets/signin.svg" class="img-fluid" style="height: 200px;" />
      </div>

      <div class="col-sm-6 user-forms-container">
        <%= form_tag user_companies_find_path, method: :post, remote: true, authenticity_token: true do %>
          <div class="field form-group">
            <label>Email: </label>
            <%= email_field_tag :email, nil, class: 'form-control', placeholder: 'john.doe@gmail.com' %>
          </div>

          <div class="actions text-right">
            <button class="btn btn-secondary btn-sm" type="submit">Continue</button>
          </div>
        <% end %>
        <div class="text-center">
          <hr>
          <em class="text-muted">Don't Have an Account?&nbsp;</em>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-sm btn-outline-secondary"  %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/user_companies/find_user_by_email_response.js.erb
<% if @found_users.count == 0 %>
  alert("Invalid Email.");
<% elsif @found_users.count == 1  %>
  window.location.replace("<%= new_user_session_url(subdomain: @found_users.first.company.subdomain, user_email: @found_users.first.email) %>");
<% else %>
  window.location.replace('<%= show_companies_path(user_email: @found_users.first.email) %>');
<% end %>

app/views/user_companies/show_companies.html.erb
<div class="row">
  <div class="offset-sm-3 col-sm-6">
    <div class="card shodowed-card">
      <h2 class="card-header">Select a Company</h2>
      <div class="card-body">
       <div class="list-group">
        <% @companies.each do |company| %>
          <%= link_to company.name, new_user_session_url(subdomain: company.subdomain, user_email: @email), data: { confirm: "Proceed to #{company.name}?" }, class: 'list-group-item list-group-item-action' %>
        <% end %>
        </div> 
      </div>
    </div>
  </div>
</div>