config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    member do
      get 'add_membership'
      delete 'remove_member'
      get 'approve_request'
      get 'reject_request'
    end
  end

  root 'home#index'

  resources :issues, only: :index do
    get 'filter', on: :collection
    get 'history', on: :member
    resources :comments, shallow: true
    resources :documents, except: :destroy
  end

  resources :projects do
    resources :documents, except: :destroy
    resources :comments, shallow: true
    resources :issue_types, except: :destroy
    resources :project_memberships, only: %i[index create], as: 'members'
    resources :issues, only: [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :documents do
    delete :destroy
  end

  resources :comments, only: [:edit, :update, :destroy]

  resources :issue_states do
    get :autocomplete_issue_title, on: :collection
  end

  resources :project_memberships, only: :destroy do
    collection do
      get 'search'
    end
  end

  resources :issue_types do
    get :autocomplete_project_title, on: :collection
  end

  get 'user_companies/find', to: 'user_companies#find'
  post 'user_companies/find', to: 'user_companies#find_user_by_email'
  get 'user_companies/show_companies', to: 'user_companies#show_companies', as: :show_companies
  get 'sidebar_toggle/:is_collapsed', to: 'application#sidebar_toggle'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    get 'users/sign_up/verify_subdomain_availability', to: 'users/registrations#verify_subdomain_availability'
  end

  get 'reports/issues', to: 'reports#issues', as: 'issues_report'
  get 'workplace', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/issues', to: 'dashboard#issues', as: 'dashboard_issues'

  resources :members do
    member do
      get 'privileges', action: 'privileges_show'
      get 'change_password_form', action: 'show_change_password_form'
      put 'change_password', action: 'change_password'
    end
    collection do
      get 'privileges'
    end
  end

  resources :issue_watchers do
    collection do
      get 'search'
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  sequenceid :company, :projects
  has_associated_audits

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 3, maximum: 1024 }

  belongs_to :company
  has_many   :issues, dependent: :destroy
  has_many   :issue_types

  has_many :comments, as: :commentable
  has_many :documents, as: :documentable
  has_many :comments, as: :commentable, dependent: :destroy

  # Polymorphic Team/User
  has_many :project_memberships
  # has_many :project_members, through: :project_memberships
  has_many :teams, through: :project_memberships, source: :project_member,
  source_type: 'Team'
  has_many :users, through: :project_memberships, source: :project_member,
  source_type: 'User'

  def dependent_issues?
    issues.count > 0
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource find_by: 'sequence_num'
  add_breadcrumb 'Projects', :projects_path

  def index
    respond_to do |format|
      format.html
    end
  end

  def new
    add_breadcrumb 'New Project', :new_project_path
    respond_to do |format|
      format.html
    end
  end

  def create
    if @project.save
      flash[:notice] = t('projects.create.success')
      redirect_to @project
    else
      flash.now[:error] = @project.errors.full_messages
      render :new
    end
  end

  def show
    add_breadcrumb @project.title, :project_path
    @document = current_tenant.documents.new
    @issues = @project.issues
    @issue_types = current_tenant.issue_types.for_projects(@project)
    @issue_states = current_tenant.issue_states.for_projects(@project)
    @comments = @project.comments
    @comment = current_tenant.comments.new
    respond_to do |format|
      format.html
    end
  end

  def edit
    add_breadcrumb @project.title, :project_path
    add_breadcrumb 'Edit', :edit_project_path
    respond_to do |format|
      format.html
    end
  end

  def update
    if @project.update(project_params)
      flash[:notice] = t('projects.update.success')
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    if @project.dependent_issues?
      flash[:error] = t('projects.destroy.dependent_issues', count: @project.issues.count)
    else
      @project.destroy
      if @project.destroyed?
        flash[:notice] = t('projects.destroy.success')
      else
        flash[:error] = @project.errors.full_messages
      end
    end
    respond_to do |format|
      format.html { redirect_to projects_path }
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div>
    <%= f.submit class: 'btn btn-secondary float-right' %>
  </div>
<% end %>

app/views/projects/_highprioritybtn.html.erb
<button type="button" class="btn btn-danger btn-sm">High</button>

app/views/projects/_issuestatebtn.html.erb
<button type="button" class="btn btn-secondary btn-sm"><i class="material-icons">done</i> Resolved</button>

app/views/projects/_lowprioritybtn.html.erb
<button type="button" class="btn btn-info btn-sm">Low</button>

app/views/projects/_mediumprioritybtn.html.erb
<button type="button" class="btn btn-warning btn-sm">Medium</button>

app/views/projects/_newcomment.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  *Modal content comes here*
</div>
<div class="modal-footer">
  <button class="btn btn-secondary">Save</button>
</div>

app/views/projects/_project.html.erb
<tr>
  <td><%= link_to project.title, project%></td>
  <td><%= project.description%></td>
  <td><span><%= link_to project.issues.size, project, class: 'btn btn-sm font-weight-bold', id: 'projects_issues_count_td' %></span></td>
  <td><%= time_ago_in_words(project.updated_at) %> ago</td>
</tr>

app/views/projects/_resolved.html.erb
<button type="button" class="btn rounded-button btn-elegant btn-small">Resolved</button>

app/views/projects/_unresolved.html.erb
<button type="button" class="btn rounded-button btn-danger btn-small">Unresolved</button>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= render 'form' %>
<%= link_to 'Back', project_path(@project), class: 'btn btn-secondary float-right mr-2' %>

app/views/projects/index.html.erb
<h1 class="float-left">Projects</h1>
<% if can? :create, :Project %>
  <%= link_to 'New Project', new_project_path, class: 'btn btn-secondary float-right' %>
<% end %>
<br><br><br>
<div class="spinner-border text-secondary"></div>
<table class="table table-hover" id="projects_table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Issues</th>
      <th scope="col">Last Updated</th>
    </tr>
  </thead>
  <tbody>
    <%= render @projects %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path, class: 'btn btn-secondary float-right mr-2 mb-5' %>

app/views/projects/show.html.erb
<h1 class="float-left"><%= @project.title %></h1>
<% if can? :index, IssueType %>
  <%= link_to 'Add Custom Issue Type', project_issue_types_path(@project),class: 'btn btn-secondary float-right mr-2' %>
<% end %>
<% if can? :edit, Project %>
  <%= link_to 'Edit Project', edit_project_path(@project),class: 'btn btn-secondary float-right mr-2' %>
<%end%>
<% if can? :delete, Project %>
  <%= link_to 'Delete Project', project_path(@project),class: 'btn btn-secondary float-right mr-2', method: 'delete', data: { confirm: 'Are you sure?' } %>
<% end %>
<a class="btn btn-secondary float-right mr-2" href= "<%= project_members_path(@project) %>">

  <i class="fas fa-users mr-2"></i>Members
</a>
<br><br><br>

<p class="h5 text-muted jumbotron"><%= @project.description %></p>

<h2 class="float-left">Issues</h2>
<%= link_to 'New Issue', new_project_issue_path(@project), class: 'btn btn-secondary float-right'%>
<br><br><br>

<table class="table table-hover" id="projects_issues_table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Assignee</th>
      <th scope="col">Issue Type</th>
      <th scope="col">Status</th>
      <th scope="col">Priority</th>
      <th scope="col">Created</th>
      <th scope="col">Due Date</th>
    </tr>
  </thead>
  <tbody id="projects_list">
    <%= render partial: "issues/issues", locals: { issues: @issues } %>
  </tbody>
</table>
<br>
<ul class="nav nav-tabs mb-4" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="pill" href="#pills_document" role="tab" aria-controls="pills_document" aria-selected="false">Documents</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="pill" href="#pills_comment" role="tab" aria-controls="pills_comment" aria-selected="false">Comments</a>
  </li>
</ul>

<div class="tab-content mb-5">
  <div class="tab-pane fade show active" id="pills_document" role="tabpanel" aria-labelledby="pills_timeline_tab">
    <div class="page-header">
      <button type="button" class="btn btn-secondary float-right" data-toggle="modal" data-target="#upload_document_modal">Upload Document</button>
      <%= render partial: 'documents/upload_document_modal' %>
    </div>
    <br><br><br>
    <%= render partial: "documents/show_documents", locals: { documents: @project.documents } %>
  </div>

  <div class="tab-pane fade" id="pills_comment" role="tabpanel" aria-labelledby="pills_timeline_tab">
    <%= render partial: 'comments/comment', locals: { commentable_object: @project, comment: @comment, comments: @comments } %>
  </div>
</div>