config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    member do
      get 'add_membership'
      delete 'remove_member'
      get 'approve_request'
      get 'reject_request'
    end
  end

  root 'home#index'

  resources :issues, only: :index do
    get 'filter', on: :collection
    get 'history', on: :member
    resources :comments, shallow: true
    resources :documents, except: :destroy
  end

  resources :projects do
    resources :documents, except: :destroy
    resources :comments, shallow: true
    resources :issue_types, except: :destroy
    resources :project_memberships, only: %i[index create], as: 'members'
    resources :issues, only: [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :documents do
    delete :destroy
  end

  resources :comments, only: [:edit, :update, :destroy]

  resources :issue_states do
    get :autocomplete_issue_title, on: :collection
  end

  resources :project_memberships, only: :destroy do
    collection do
      get 'search'
    end
  end

  resources :issue_types do
    get :autocomplete_project_title, on: :collection
  end

  get 'user_companies/find', to: 'user_companies#find'
  post 'user_companies/find', to: 'user_companies#find_user_by_email'
  get 'user_companies/show_companies', to: 'user_companies#show_companies', as: :show_companies
  get 'sidebar_toggle/:is_collapsed', to: 'application#sidebar_toggle'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    get 'users/sign_up/verify_subdomain_availability', to: 'users/registrations#verify_subdomain_availability'
  end

  get 'reports/issues', to: 'reports#issues', as: 'issues_report'
  get 'workplace', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/issues', to: 'dashboard#issues', as: 'dashboard_issues'

  resources :members do
    member do
      get 'privileges', action: 'privileges_show'
      get 'change_password_form', action: 'show_change_password_form'
      put 'change_password', action: 'change_password'
    end
    collection do
      get 'privileges'
    end
  end

  resources :issue_watchers do
    collection do
      get 'search'
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  authorize_resource class: false
  add_breadcrumb 'Issues Report', :issues_report_path

  def issues
    @issues = current_tenant.issues.includes(:project, :assignee, :creator, :issue_state, :issue_type)
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def issue_priority(issue)
    Issue::PRIORITY.key(issue.priority)
  end
end

app/views/reports/_issue_audit_row.html.erb
<% if audit.action == 'update' %>
  <tr>
    <td><%= audit_counter%></td>
    <td><%= audit.created_at.strftime("%b %d %Y %I:%M %p") %></td>
    <td>
      <%= render partial: 'issue_history_nested_table_for_attribute', locals: {audit: audit} %>
    </td>
    <td>
      <%= render partial: 'issue_history_nested_table_for_from', locals: {audit: audit} %>
    </td>
    <td>
      <%= render partial: 'issue_history_nested_table_for_to', locals: {audit: audit} %>
    </td>
  </tr>  
<% end %>

app/views/reports/_issue_history_nested_table_for_attribute.html.erb
<table class="table table-sm">
  <% audit.audited_changes.keys.each do |key| %>
    <tr>
      <td>
        <% if assignee_id_key?(key) %>
          <%= 'Assignee' %>
        <% else %>
          <%= key.titleize %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/reports/_issues_report.html.erb
<tr>
  <td><%= link_to(issue.title, project_issue_path(issue.project, issue.sequence_num)) %></td>
  <td><%= link_to(issue.project.title, project_path(issue.project)) %></td>
  <% if issue.assignee.present? %>
    <td><%= link_to(issue.assignee.full_name, member_path(issue.assignee)) %></td>
  <% else %>
    <td>--</td>
  <% end %>
  <td><%= link_to(issue.creator.full_name, member_path(issue.creator)) %></td>
  <td><%= issue.issue_state.name %></td>
  <td><%= issue.issue_type.name %></td>
  <td><span class="badge badge-pill badge-<%= badge_class_from_priority(issue.priority) %>"><%= issue_priority(issue) %></span></td>
  <td><%= issue.start_date %></td>
  <td><%= issue.due_date %></td>
</tr>

app/views/reports/issue_history.html.erb
<div class="text-center my-4">
  <h1><%= @issue.title %> History Report</h1>
</div>

<div class="my-4">
  <table id="report_datatable"  class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Sr#</th>
        <th scope="col">Time</th>
        <th scope="col">Attribute</th>
        <th scope="col">From</th>
        <th scope="col">To</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'issue_audit_row', collection: @audits, as: :audit %>
    </tbody>
  </table>
</div>

app/views/reports/issues.html.erb
<div class="wrapper mb-4">
  <h1 class="float-left">Issues Report</h1>
  <div class="float-right" id="datatable_buttons"></div>
</div>

<div class="my-4">
  <table id="report_datatable"  class="table table-sm">
    <thead>
      <tr>
      <th scope="col">Title</th>
      <th scope="col">Project</th>
      <th scope="col">Assignee</th>
      <th scope="col">Creator</th>
      <th scope="col">State</th>
      <th scope="col">Type</th>
      <th scope="col">Priority</th>
      <th scope="col">Created</th>
      <th scope="col">Due Date</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'issues_report', collection: @issues, as: :issue %>
    </tbody>
  </table>
</div>